### ISSUE TITLE
Enhance nextsubnet command to ignore blocks occupied by hosts

### ISSUE THREAD

**Issue by kd7lxl** [HamWAN/hamwan-portal#23]
https://github.com/HamWAN/hamwan-portal/blob/d673469c4f415232808147776db7a2875b738e96/portal/management/commands/nextsubnet.py#L27

**Comment by bkus** [comment]
I have no idea what a "block" is.  Is that defined somewhere?

**Comment by kd7lxl** [comment]
"block" in this context is a Subnet instance.
